# Generated by Django 6.0.3 on 2026-03-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foruns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='description',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='title',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='updated_at',
        ),
    ]
