# Generated by Django 6.0.3 on 2026-04-05 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foruns', '0001_initial'),
        ('users', '0002_profile_lastname_profile_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postresponse',
            old_name='answer',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='postresponse',
            name='content',
        ),
        migrations.AddField(
            model_name='postresponse',
            name='response',
            field=models.TextField(default=0, verbose_name='Resposta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postresponse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
