# Generated by Django 6.0.3 on 2026-03-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foruns', '0003_forum_active_forum_created_at_forum_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fórum', 'verbose_name_plural': 'Fóruns'},
        ),
        migrations.AlterModelOptions(
            name='likecomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Like de Comentário', 'verbose_name_plural': 'Likes de Comentários'},
        ),
        migrations.AlterModelOptions(
            name='likereply',
            options={'ordering': ['-created_at'], 'verbose_name': 'Like de Resposta', 'verbose_name_plural': 'Likes de Respostas'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at'], 'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='forum',
        ),
    ]
