# Generated by Django 6.0.3 on 2026-04-05 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do Passaporte'),
        ),
        migrations.AddField(
            model_name='profile',
            name='protocal_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do Protocolo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='visa_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do Visto'),
        ),
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('birth_certificate', 'Certidão de Nascimento'), ('passport', 'Passaporte'), ('cover_letter', 'Carta de Apresentação')], max_length=255, verbose_name='Tipo do Documento')),
                ('document', models.FileField(upload_to='documents/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
